<?php
/**
 * @file
 * Helps creating customizable lists of content
 * that can be placed anywhere as a block
 */

define('NL_SINGLE', 'single');
define('NL_LIST', 'item_list');
define('NL_CAROUSEL', 'carousel');
define('NL_CAROUSEL_ALT', 'carousel_alt');
define('NL_POLL', 'poll');

define('NL_COL_FULL', 'full');
define('NL_COL_HALF', 'half');
define('NL_COL_THIRD', 'third');
define('NL_COL_QRT', 'quarter');

function nodelist_get_column_map() {
  return array(
    NL_COL_FULL   => 1,
    NL_COL_HALF   => 2,
    NL_COL_THIRD  => 3,
    NL_COL_QRT    => 4,
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 * This lets ctools know to scan the module for a content_type plugin file.
 */
function nodelist_ctools_plugin_directory($module, $plugin) {
  // we'll be nice and limit scandir() calls
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_menu().
 */
function nodelist_menu() {
  $items = array();

  $items['nodelist/autocomplete/%'] = array(
    'page callback' => 'nodelist_autocomplete',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function nodelist_theme($existing, $type, $theme, $path) {
  $path .= '/templates';

  $themes = array(
    'nodelist_list' => array(
      'render element' => 'form',
    ),
    'nodelist_single' => array(
      'path' => $path,
      'template' => 'nodelist-single',
      'variables' => array('items' => NULL, 'conf' => NULL),
    ),
    'nodelist_item_list' => array(
      'path' => $path,
      'template' => 'nodelist-item-list',
      'variables' => array('items' => NULL, 'conf' => NULL),
    ),
    'nodelist_carousel' => array(
      'path' => $path,
      'template' => 'nodelist-carousel',
      'variables' => array('items' => NULL, 'conf' => NULL),
    ),
    'nodelist_carousel_alt' => array(
      'path' => $path,
      'template' => 'nodelist-carousel-alt',
      'variables' => array('items' => NULL, 'conf' => NULL),
    ),
    'nodelist_poll' => array(
      'path' => $path,
      'template' => 'nodelist-poll',
      'variables' => array('items' => NULL, 'conf' => NULL),
    ),
  );

  return $themes;
}

function template_preprocess_nodelist_single(&$variables){
	_template_preprocess_nodelist_items($variables, 'medium');
}
function template_preprocess_nodelist_item_list(&$variables){
	_template_preprocess_nodelist_items($variables, 'thumbnail');
}
/**
* Implements template_preprocess_hook
*/
function _template_preprocess_nodelist_items(&$variables, $image_preset){
	foreach ($variables['items'] as $nid => &$item) {
		if (!empty($variables['conf']['more_link_target'])) {
			$link = $variables['conf']['more_link_target'];
		}
		else {
			$link = 'node/' . $item->nid;
		}
    $sponsor = FALSE;
    $path = '';

    switch ($variables['items'][$nid]->type) {
      case 'haven_article':
        $path = $variables['items'][$nid]->field_haven_article_image_main['und'][0]['uri'];
        break;
      case 'haven_event':
        $path = $variables['items'][$nid]->field_haven_event_image_main['und'][0]['uri'];
        break;
      case 'haven_garden':
        $path = $variables['items'][$nid]->field_haven_garden_images['und'][0]['uri'];
        break;
      case 'haven_page':
        $path = $variables['items'][$nid]->field_haven_page_image_main['und'][0]['uri'];
        break;
      case 'haven_press':
        $path = $variables['items'][$nid]->field_haven_press_image['und'][0]['uri'];
        break;
      case 'haven_answers':
        $path = $variables['items'][$nid]->field_haven_answers_image_main['und'][0]['uri'];
        break;
    }

    $variables['items'][$nid]->image_link = '';
    if ($path != '') {
      $image = array(
          'style_name' => $image_preset, // style name
          'path' => $path,
          'alt' => $item->title,
          'title' => $item->title,
          );
      $variables['items'][$nid]->image_link = l(theme('image_style', $image), $link, array('html' => TRUE));
    }

		$variables['items'][$nid]->body_link = '';
    $variables['items'][$nid]->title_link = l(truncate_utf8($item->title, 70, TRUE), $link);

    if (isset($item->body)) {
			$variables['items'][$nid]->body_link = l(truncate_utf8($item->body['und'][0]['safe_summary'], 200, TRUE),
			$link, array('html' => TRUE));
		}

    if ($sponsor) {
      $variables['items'][$nid]->title_link = (truncate_utf8($subtitle, 70, TRUE));
      $variables['items'][$nid]->image_link = (theme('image_style', $image));
    }
	}
}

/**
 * Autocomplete function that gives the available nodes
 */
function nodelist_autocomplete($type = FALSE, $title = '') {
  $nodes = array();

  $result = db_query("SELECT nid, title FROM {node} WHERE type = :type AND title LIKE :title", array(':type' => $type, ':title' => '%' . $title . '%'));
  $nodes = $result->fetchAllKeyed();

  // Make a beatifull select
  $formatted_result = array();
  foreach ($nodes as $nid => $title) {
    $formatted_result[$title . " [nid:$nid]"] = $title;
  }

  drupal_json_output($formatted_result);
}

/**
 * Helper form for a single selected node
 */
function _nodelist_selected_node($key, $type= 'player', $node = NULL, $weight = 0, $size = 10) {
  $form = array(
    '#tree' => TRUE,
    '#weight' => $weight,
  );

  // Set default value for 'node'
  $node_default =  (!is_null($node) && isset($node['node'])) ? $node['node'] : '';
  $form['node'] = array(
    '#type' => 'textfield',
    '#title' => t('Select new node to add to list'),
    '#title_display' => 'invisible',
    '#autocomplete_path' => 'nodelist/autocomplete/' . $type,
    '#parents' => array('selected_nodes', $key, 'node'),
    '#default_value' => $node_default,
  );

  $form['nid'] = array(
    '#type' => 'value',
    '#value' => NULL,
    '#parents' => array('selected_nodes', $key, 'nid'),
  );

  // Set default value for 'nid' if not empty field
  if (!is_null($node) && isset($node['nid']) && ctype_digit($node['nid'])) {
    $form['nid']['#value'] = $node['nid'];
  } elseif (!is_null($node) && isset($node['node'])) {
    $tmp_node = explode(':', $node);
    $tmp_node = array_pop($tmp_node);
    $tmp_node = substr($tmp_node, 0, -1);
    if (ctype_digit($tmp_node)) {
      $node['nid'] = $tmp_node;
    }
  }

  $form['type'] = array(
    '#type' => 'value',
    '#value' => $type,
    '#parents' => array('selected_nodes', $key, 'type'),
  );

  $form['weight'] = array(
    '#type' => 'weight',
    '#title' => $nid !== '' ? t('Weight for node @label', array('@label' => $nid)) : t('Weight for new choice'),
    '#title_display' => 'invisible',
    '#default_value' => $weight,
    '#delta' => 50,
    '#parents' => array('selected_nodes', $key, 'weight'),
  );

  return $form;
}

/**
 * Helper theming function
 */
function theme_nodelist_list($variables) {
  $form = $variables['form'];

  drupal_add_tabledrag('nodelist-selected-table', 'order', 'sibling', 'nodelist-weight');

  $is_admin = user_access('administer nodes');
  $delta = 0;
  $rows = array();
  $headers = array('', t('Selected content'));
  $headers[] = t('Weight');

  foreach (element_children($form) as $key) {
    $delta++;
    // Set special classes for drag and drop updating.
    $form[$key]['weight']['#attributes']['class'] = array('nodelist-weight');

    // Build the table row.
    $row = array(
      'data' => array(
        array('class' => array('choice-flag')),
        drupal_render($form[$key]['node']),
      ),
      'class' => array('draggable'),
    );
    $row['data'][] = drupal_render($form[$key]['weight']);

    // Add any additional classes set on the row.
    if (!empty($form[$key]['#attributes']['class'])) {
      $row['class'] = array_merge($row['class'], $form[$key]['#attributes']['class']);
    }

    $rows[] = $row;
  }

  $output = theme('table', array('header' => $headers, 'rows' => $rows, 'attributes' => array('id' => 'nodelist-selected-table')));
  $output .= drupal_render_children($form);
  return $output;
}

/**
 * Custom submit function to add more choices
 */
function nodelist_more_submit(&$form, &$form_state) {
  // Add new node to list
  if ($form_state['values']['op'] == $form_state['values']['nodelist_more']) {
    $form_state['values']['selected_nodes_count'] = count($form_state['values']['selected_nodes']) + 1;

    unset($form_state['input']['selected_nodes']);
  }

  // Change node types
  if ($form_state['values']['op'] == $form_state['values']['content_type_select']) {
    foreach ($form_state['values']['selected_nodes'] as $key => $node) {
      if (($node['type'] != $form_state['values']['content_type'])) {
        unset($form_state['values']['selected_nodes'][$key]);
      }
    }

    // Removing empty nodes
    foreach ($form_state['values']['selected_nodes'] as $key => $node) {
      if (empty($node['node'])) {
        unset($form_state['values']['selected_nodes'][$key]);
      }
    }

    unset($form_state['input']['selected_nodes']);
    unset($form_state['input']['content_type']);
  }

  foreach ($form_state['values']['selected_nodes'] as $key => $node) {
    if (!empty($node['node'])) {
      $tmp_nid = explode(':', $node['node']);
      $tmp_nid = array_pop($tmp_nid);
      $tmp_nid = substr($tmp_nid, 0, -1);
      // TODO: Implement more complex check for given title + ID
      if (ctype_digit($tmp_nid)) {
        $form_state['values']['selected_nodes'][$key]['nid'] = $tmp_nid;
      }
    }
  }
  // Saving all the values of the form
  $form_state['conf']['selected_nodes'] = $form_state['values']['selected_nodes'];
  $form_state['conf']['columns'] = $form_state['values']['columns'];
  $form_state['conf']['title_text'] = $form_state['values']['title_text'];
  $form_state['conf']['node_format'] = $form_state['values']['node_format'];
  $form_state['conf']['content_type'] = $form_state['values']['content_type'];
  $form_state['conf']['list_type'] = $form_state['values']['list_type'];
  $form_state['conf']['columns'] = $form_state['values']['columns'];
  $form_state['conf']['title_text'] = $form_state['values']['title_text'];
  $form_state['conf']['more_text'] = $form_state['values']['more_text'];
  $form_state['conf']['more_link'] = $form_state['values']['more_link'];

  $form_state['rebuild'] = TRUE;
}

function nodelist_js($form, &$form_state) {
  return $form['nodelist_nodes']['selected_nodes'];
}


/**
 * 'Edit form' callback for the content type.
 */
function nodelist_nodelist_content_type_edit_form($form, &$form_state) {

  // Caching form for correct workflow
  $form_state['cache'] = TRUE;

  if (isset($form_state['values']['selected_nodes_count'])) {
    $node_count = $form_state['values']['selected_nodes_count'];
  } else {
    $node_count = empty($form_state['values']['selected_nodes']) ? 1 : count($form_state['values']['selected_nodes']);
  }

  $conf = $form_state['conf'];
  drupal_add_js(drupal_get_path('module', 'nodelist') . '/js/admin.js', 'file');

  $node_types = node_type_get_names();
  if (empty($node_types)) {
    drupal_set_message(t('No content types were found, please add one first.'), 'error', FALSE);
  }

  $list_types = array(
    NL_SINGLE   => t('Single node'),
    NL_LIST     => t('List of nodes'),
    NL_CAROUSEL => t('Carousel'),
    NL_CAROUSEL_ALT => t('Alternative carousel'),
    NL_POLL => t('Poll'),
  );

  $node_type = isset($conf['content_type']) ? $conf['content_type'] : current(array_keys($node_types));

  $default_conf = array(
    'content_type' => $node_type,
    'list_type' => NL_LIST,
    'node_format' => 'teaser',
    'columns' => NL_COL_FULL,
    'more_btn_text' => t('More'),
    'more_btn_link' => '',
    'teaser_length' => 200,
  );

  $form['#prefix'] = '<div id="nodelist-form-wrapper">';
  $form['#suffix'] = '</div>';

  $form['nodelist_nodes'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#tree' => FALSE,
    '#title' => t('General settings'),
    '#description' => t('Select the content of the list'),
    '#collapsible' => FALSE,
    '#prefix' => '<div class="clear-block" id="nodelist-wrapper">',
    '#suffix' => '</div>',
    '#weight' => -3,
  );

  $form['nodelist_nodes']['selected_nodes'] = array(
    '#prefix' => '<div id="nodelist-selected-nodes">',
    '#suffix' => '</div>',
    '#theme' => 'nodelist_list',
    '#tree' => TRUE,
    '#weight' => -1,
  );

  $form['nodelist_nodes']['content_type'] = array(
    '#type' => 'select',
    '#title' => t('Content type'),
    '#required' => TRUE,
    '#default_value' => isset($conf['content_type']) ? $conf['content_type'] : $default_conf['content_type'],
    '#options' => $node_types,
    '#description' => t('Select the content type of the list\'s items.'),
    '#weight' => -3,
    '#ajax' => array(
      'wrapper' => 'nodelist-selected-nodes',
      'callback' => 'nodelist_js',
      'method' => 'replace',
      'effect' => 'fade'
    ),
  );

  $form['nodelist_nodes']['content_type_select'] = array(
    '#type' => 'submit',
    '#value' => t('Choose'),
    '#weight' => -2,
    '#submit' => array('nodelist_more_submit'),
    '#ajax' => array(
      'wrapper' => 'nodelist-selected-nodes',
      'callback' => 'nodelist_js',
      'method' => 'replace',
      'effect' => 'fade'
    ),
    '#attributes' => array(
      'style' => 'display:none;',
    ),
  );

  // Get all nodes'
  $delta = 0;
  $weight = 0;
  $max_weight = $weight;

  // Check if form is ment to be rebuild thanks to an ajax request from the select element
  if (!empty($form_state['triggering_element']) && $form_state['triggering_element']['#name'] == 'content_type') {
    $node_count = 1;
    $node_type = $form_state['triggering_element']['#value'];
    $conf['selected_nodes'] = array();
    $form_state['values']['selected_nodes'] = array();
    $form_state['conf']['selected_nodes'] = array();
    unset($form_state['input']['selected_nodes']);

    $form_state['rebuild'] = TRUE;
  }

  if (isset($conf['selected_nodes']) && ($conf['content_type'] == $conf['selected_nodes'][0]['type'])) {
    $delta = count($conf['selected_nodes']);
    foreach ($conf['selected_nodes'] as $key => $node) {
      $weight = $node['weight'];
      $max_weight = ($max_weight < $weight) ? $weight : $max_weight;
      $form['nodelist_nodes']['selected_nodes'][$key] = _nodelist_selected_node($key, $node_type, $node, $weight, $node_count);
    }
  }

  // Add new node field
  $existing_delta = $delta;
  $weight = ++$max_weight;
  for ($delta; $delta < $node_count; $delta ++) {
    $key = $delta;
    $form['nodelist_nodes']['selected_nodes'][$key] = _nodelist_selected_node($key, $node_type, NULL, $weight, $node_count);
  }

  $form['nodelist_nodes']['nodelist_more'] = array(
    '#type' => 'submit',
    '#value' => t('Add more'),
    '#weight' => 1,
    '#submit' => array('nodelist_more_submit'),
    '#ajax' => array(
      'wrapper' => 'nodelist-selected-nodes',
      'callback' => 'nodelist_js',
      'method' => 'replace',
      'effect' => 'fade'
    ),
  );


  $form['nodelist_content'] = array(
    '#type' => 'fieldset',
    '#title' => t('Visualisation settings'),
    '#collapsible' => FALSE,
    '#description' => t('Define custom visualization settings'),
    '#weight' => -2,

  );

  // Set up all the available view modes for this type of nodes
  $entity = entity_get_info('node');
  $node_formats = array();
  foreach ($entity['view modes'] as $view_mode => $settings) {
    $node_formats[$view_mode] = $settings['label'];
  }
  $form['nodelist_content']['node_format'] = array(
    '#type' => 'select',
    '#title' => t('Node format'),
    '#required' => TRUE,
    '#default_value' => isset($conf['node_format']) ? $conf['node_format'] : $default_conf['node_format'],
    '#options' => $node_formats,
    '#description' => t('Select how to display the nodes')
  );

  $form['nodelist_content']['list_type'] = array(
    '#type' => 'select',
    '#title' => t('List type'),
    '#required' => TRUE,
    '#default_value' => isset($conf['list_type']) ? $conf['list_type'] : $default_conf['list_type'],
    '#options' => $list_types,
    '#description' => t('If single node selected, only the first node will be rendered')
  );

  $form['nodelist_content']['columns'] = array(
    '#type' => 'select',
    '#title' => 'Width (columns)',
    '#options' => array(
      NL_COL_FULL   => t('full width'),
      NL_COL_HALF   => '1/2',
      NL_COL_THIRD  => '1/3',
      NL_COL_QRT    => '1/4'
    ),
    '#default_value' => isset($conf['columns']) ? $conf['columns'] : $default_conf['columns']
  );

  $form['nodelist_options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Additional options'),
    '#collapsible' => FALSE,
    '#description' => t('Custom title text or "More" button'),
    '#weight' => -1,

    'title_text' => array(
      '#type' => 'textfield',
      '#title' => t('Headbar text or title'),
      '#description' => t('Enter a title to be shown above the node(s). Leave empty not to show anything.'),
      '#required' => FALSE,
      '#default_value' => isset($conf['title_text']) ? $conf['title_text'] : '',
    ),

    'more_text' => array(
      '#type' => 'textfield',
      '#title' => t('"More" button text'),
      '#required' => FALSE,
      '#default_value' => isset($conf['more_text']) ? $conf['more_text'] : $default_conf['more_text'],
    ),

    'more_link' => array(
      '#type' => 'textfield',
      '#title' => t('"More" button link'),
      '#required' => FALSE,
      '#description' => t('Enter local Drupal path or external URL starting with http(s).'),
      '#default_value' => isset($conf['more_link']) ? $conf['more_link'] : $default_conf['more_link'],
    ),
  );

  // Use custom title options.
  unset($form['override_title']);
  unset($form['override_title_text']);
  return $form;
}

/**
 * Edit form validate function.
 */
function nodelist_nodelist_content_type_edit_form_validate($form, &$form_state) {

  // Validating selected nodes
  if (!count($form_state['values']['selected_nodes'])) {
    form_set_error('nodes', t('No nodes were selected.'));
  }

  if (!empty($form_state['values']['more_link'])) {
    if (!drupal_valid_path($form_state['values']['more_link'])) {
      if (!valid_url($form_state['values']['more_link'], TRUE)) {
        form_set_error('more_link', t('External links must begin with "http" or "https".'));
      }
    }
    // Handles <front>
    if ($form_state['values']['more_link'] == '<front>') {
      $form_state['values']['more_link'] = 'http://' . $_SERVER['SERVER_NAME'] . '/';
    }
  }
}

/**
 * Edit form submit function.
 */
function nodelist_nodelist_content_type_edit_form_submit($form, &$form_state) {

  // Removing empty nodes
  foreach ($form_state['values']['selected_nodes'] as $key => $node) {
    if (empty($node['node'])) {
      unset($form_state['values']['selected_nodes'][$key]);
    } else {
      $tmp_nid = explode(':', $node['node']);
      $tmp_nid = array_pop($tmp_nid);
      $tmp_nid = substr($tmp_nid, 0, -1);
      // TODO: Implement more complex check for correct title of the given ID
      if (ctype_digit($tmp_nid)) {
        $form_state['values']['selected_nodes'][$key]['nid'] = $tmp_nid;
      }
    }
  }

  // Anything in $form_state['conf'] will be saved automatically.
  $form_state['conf']['selected_nodes'] = $form_state['values']['selected_nodes'];
  $form_state['conf']['node_format'] = $form_state['values']['node_format'];
  $form_state['conf']['content_type'] = $form_state['values']['content_type'];
  $form_state['conf']['list_type'] = $form_state['values']['list_type'];
  $form_state['conf']['columns'] = $form_state['values']['columns'];
  $form_state['conf']['title_text'] = $form_state['values']['title_text'];
  $form_state['conf']['more_text'] = $form_state['values']['more_text'];
  $form_state['conf']['more_link'] = $form_state['values']['more_link'];
}

/**
 * Block's title in panel editing interface.
 */
function nodelist_content_type_admin_title($subtype, $conf, $context = NULL) {
  // Check only for 'nodelist' panes
  if ($subtype == 'nodelist') {
    if ($conf['title_text'] && !empty($conf['title_text'])) {
      $output = filter_xss_admin($conf['title_text']);
    }
    else {
      $output = t('Width: one @cols', array('@cols' => $conf['columns']));
    }
    return $output;
  }
}

/**
 * Callback to provide administrative info (the preview in panels when building
 * a panel).
 */
function nodelist_content_type_admin_info($subtype, $conf, $context = NULL) {
  $block = new stdClass();
  $block->title = t('Width: one @cols', array('@cols' => $conf['columns']));
  $block->content = '';
  return $block;
}

/**
 * Run-time rendering of the body of the list.
 *
 * @param $subtype Content type sub-type
 * @param $conf Configuration as done at admin time.
 * @param $args
 * @param $context
 *
 * @return
 *   An object with at least title and content members.
 */
function nodelist_content_type_render($subtype, $conf, $args, $context) {
  $block = new stdClass();

  $columns = $conf['columns'];

  // Prepare classes
  $classes = array();
  $classes[] = 'nodelist';
  $classes[] = 'nodelist-' . $conf['list_type'];
  $classes[] = 'nodelist-col-' . $columns;

  // Build title
  $title = NULL;
  if (!empty($conf['title_text'])) {
    $title = check_plain($conf['title_text']);
  }

  // Build 'More' link
  $more = NULL;
  if (!empty($conf['more_link']) && !empty($conf['more_text'])) {
    $more = '<a class="nodelist-more" href="' . url($conf['more_link']) . '">' . $conf['more_text'] . '</a>';
  }

	$more_link_target = !empty($conf['more_link']) ? $conf['more_link'] : NULL;

  // Load default CSS.
  drupal_add_css(drupal_get_path('module', 'nodelist') . '/css/nodelist.css', 'file');

  // Define if this is the last column pane and apply additional style.
  $map = nodelist_get_column_map();
  $columns_layout = &drupal_static('nodelist_cols', array());
  if (empty($columns_layout[$columns])) {
    $columns_layout[$columns] = 1;
    $classes[] = 'nodelist-col-first';
  }
  else {
    $columns_layout[$columns]++;
  }

  if ($columns_layout[$columns] == $map[$columns]) {
    $classes[] = 'nodelist-col-last';
    $columns_layout[$columns] = 0;
  }

  // Render the contents

  // This line may be removed after all nodelist panes are redefined
  $raw_nodes = isset($conf['selected_nodes']) ? $conf['selected_nodes'] : array();
  $node_list = array();

  // Sort the nodes according to their weight
  $tmp_array = array();
  foreach ($raw_nodes as $key => $node) {
    $tmp_array[$key] = $node['weight'];
  }
  asort($tmp_array);
  foreach ($tmp_array as $key => $weight) {
    $node_list []= $raw_nodes[$key]['nid'];
  }

  // If we have a single node, we don't need the other nodes
  // so we take only the first one
  if (in_array($conf['list_type'], array(NL_SINGLE, NL_POLL))) {
    $node_list = array_shift($node_list);
    $node_list = array($node_list);
  }

  // Special JS fopr carousel widgets
  if (in_array($conf['list_type'], array(NL_CAROUSEL, NL_CAROUSEL_ALT))) {
    $add_carousel_js = &drupal_static(__FUNCTION__ . '_js', TRUE);
    if ($add_carousel_js) {
      drupal_add_js(drupal_get_path('module', 'nodelist') . '/js/jquery.carouFredSel-4.4.2.js', 'file');
      drupal_add_js(drupal_get_path('module', 'nodelist') . '/js/carousel.js', 'file');
      $add_carousel_js = FALSE;
    }
  }

  $nodes = node_load_multiple($node_list);
  $theme_func = 'nodelist_' . $conf['list_type'];
  $block->content = theme(
    $theme_func,
      array(
        'items' => $nodes,
        'conf' => array(
          'more' => $more,
          'more_link_target' => $more_link_target,
          'classes' => $classes,
          'format' => $conf['node_format'],
          'title' => $title,
        )
      )
  );

  return $block;
}

